logging:
  level:
    root: info
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: debug

spring:
  datasource:
    url: jdbc:ch://47.94.96.234:18123
    username: root
    password: P7HtW800kgmx
    name: ClickHouse
    type: com.clickhouse.jdbc.ClickHouseDataSource
  datasource-mysql:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/next?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: MYSQL_ROOT_PASSWORD

